name = "my-sonicjs-app-2"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

# Cloudflare account
# account_id = "f9d6328dc3115e621758a741dda3d5c4"

# Cloudflare Workers settings
workers_dev = true

# D1 Database
# Note: database_name and database_id are automatically updated by GitHub Actions
[[d1_databases]]
binding = "DB"
database_name = "sonicjs-worktree-lane711-otp-email-branding"
database_id = "5ebf5297-830e-4b84-aeb9-00c8dd6454c6"
migrations_dir = "./migrations"

# R2 Bucket for media storage (using CI bucket)
# [[r2_buckets]]
# binding = "MEDIA_BUCKET"
# bucket_name = "sonicjs-ci-media"

# KV Cache (using CI namespace)
[[kv_namespaces]]
binding = "CACHE_KV"
id = "b6d535043c9d403ea5a7c52862164abf"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Observability
[observability]
enabled = true
